version: '3.8'

services:
  api:
    build: .
    image: gojopportunities-api:latest
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release #variável de ambiente para o projeto rodar no modo de produção (otimizado)